name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4
      - name: Deploy to gh-pages
        uses: actions/deploy-to-github-pages@v4
        with:
          branch: gh-pages
          folder: .  # Or your website's output folder
